## Self-contained example of a LAMMPS simulation                                                                                                                                                  
## This uses a hybrid LAMMPS-input and Python approach                                                                                                                                                                                     
## system: Lennard-Jones Brownian Particles                                                                                                                                                                                                
## Author: Dr. Luke Davis                                                                                                                                                                                                                  
## Year: 2023                                                                                                                                                                                                                              
## E: luke.davis@ucl.ac.uk                                                                                                                                                                                                                 
                                                                                                                                                                                                                                           
from __future__ import print_function                                                                                                                                                                                                      
import numpy as np                                                                                                                                                                                                                         
import sys                                                                                                                                                                                                                                 
import random                                                                                                                                                                                                                              
import math                                                                                                                                                                                                                                
import ctypes                                                                                                                                                                                                                              
from lammps import lammps, PyLammps                                                                                                                                                                                                        
                                                                                                                                                                                                                                           
wd = "./"                                                                                                                                                                                                                                  
generic_file = f"{wd}in.activate-test" # main lammps input file                                                                                                                                                                            
                                                                                                                                                                                                                                           
## SIMULATION PARAMETERS                                                                                                                                                                                                                   
                                                                                                                                                                                                                                           
dimension = 3 # spatial dimension                                                                                                                                                                                                          
bl = 40 # box length                                                                                                                                                                                                                       
dens = 0.1 # density                                                                                                                                                                                                                       
Natoms = 400 # number of atoms (will be overwritten by lammps call)                                                                                                                                                                        
T = 1.0 # reduced temperature (all units are reduced according to LAMMPS units LJ)                                                                                                                                                         
dt = 0.004 #timestep                                                                                                                                                                                                                       
Nruns = 100 # number of total timesteps                                                                                                                                                                                                    
damp = 1.0 # inverse mobility                                                                                                                                                                                                              
#Dr = 1.0 # amplitude of orientation noise                                                                                                                                                                                                 
#v0 = 1.0 # propulsion speed                                                                                                                                                                                                               
instance = 0 # label to distinguish different random runs                                                                                                                                                                                  
#active_types = [2]                                                                                                                                                                                                                        
                                                                                                                                                                                                                                           
# INTERACTION POTENTIAL PARAMETERS                                                                                                                                                                                                         
epsilon = 10.0                                                                                                                                                                                                                             
sigma = 1.0                                                                                                                                                                                                                                
cutoff = 1.122 # this default value gives the WCA potential i.e. only repulsion (rc = 2^(1/6)*sigam ~ 1.122 when sigma = 1)                                                                                                                
                                                                                                                                                                                                                                           
unique_sim_label = f"RABPS_LAMMPS_dens{dens}_T{T}_damp{damp}_Dr{Dr}_v0{v0}_dt{dt}_Nruns{Nruns}_instance{instance}"                                                                                                                         
                                                                                                                                                                                                                                           
# seeds for random things in LAMMPS script                                                                                                                                                                                                 
seed0 = random.randint(10000,1000000)                                                                                                                                                                                                      
seed1 = random.randint(10000,1000000)                                                                                                                                                                                                      
seed2 = random.randint(10000,1000000)                                                                                                                                                                                                      
                                                                                                                                                                                                                                           
f = open(generic_file,'r')                                                                                                                                                                                                                 
lines = f.readlines()                                                                                                                                                                                                                      
f.close()                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                           
infile = wd+"in."+unique_sim_label                                                                                                                                                                                                         
                                                                                                                                                                                                                                           
# replace relevant parameters                                                                                                                                                                                                              
with open(infile,'w') as f:                                                                                                                                                                                                                
    for line in lines:                                                                                                                                                                                                                     
        line = line.replace("%NATOMS%",Natoms)                                                                                                                                                                                             
        line = line.replace("%EPSILON%",epsilon)                                                                                                                                                                                           
        line = line.replace("%SIGMA%",sigma)                                                                                                                                                                                               
        line = line.replace("%CUTOFF%",cutoff)                                                                                                                                                                                             
        line = line.replace("%SIMLABEL%",unique_sim_label)                                                                                                                                                                                 
        line = line.replace("%WD%",wd)                                                                                                                                                                                                     
        line = line.replace("%XLO%",str(-bl*0.5))                                                                                                                                                                                          
        line = line.replace("%XHI%",str(bl*0.5))                                                                                                                                                                                           
        line = line.replace("%YLO%",str(-bl*0.5))                                                                                                                                                                                          
        line = line.replace("%YHI%",str(bl*0.5))                                                                                                                                                                                           
        line = line.replace("%DENS%",str(dens))                                                                                                                                                                                            
        line =line.replace("%SEED0%",str(seed0))                                                                                                                                                                                           
        line = line.replace("%SEED1%",str(seed1))                                                                                                                                                                                          
        line = line.replace("%SEED2%",str(seed2))                                                                                                                                                                                          
        line = line.replace("%INSTANCE%",str(instance))                                                                                                                                                                                    
        line = line.replace("%DAMP%",str(damp))                                                                                                                                                                                            
        line = line.replace("%TEMP%",str(T))                                                                                                                                                                                               
        f.write(line)                                                                                                                                                                                                                      
                                                                                                                                                                                                                                           
# BEGIN LAMMPS SIMULATION                                                                                                                                                                                                                  
lmp = lammps(name="mpi")                                                                                                                                                                                                                   
lmp.file(infile)                                                                                                                                                                                                                           
L =PyLammps(ptr=lmp)                                                                                                                                                                                                                       
                                                                                                                                                                                                                                           
lmp.command(f"timestep {dt}")                                                                                                                                                                                                              
                                                                                                                                                                                                                                           
Natoms =lmp.extract_global("nlocal")                                                                                                                                                                                                       
print(f"\n\nPython Natoms = {Natoms}\n\n")                                                                                                                                                                                                 
                                                                                                                                                                                                                                           
# implement dynamics                                                                                                                                                                                                                       
                                                                                                                                                                                                                                           
while(n<Nruns):                                                                                                                                                                                                                            
    L.run(1)                                                                                                                                                                                                                               
    print(f"{L.runs[n].thermo.Step[0]} {L.runs[n].thermo.Temp[0]} ")                                                                                                                                                                       
    n+=1    
